#%RAML 1.0
title: Mulesoft
version: 1.0
baseUri: http://localhost:8081
/gamesType:
  get:
    description: Gets list of Games Type
    responses: 
      200:
        body: 
          application/json:







